// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIguXBt1PM1hpKRnigQcBDS7OYnxydrAY',
    appId: '1:1096466446925:web:f709e937efcd3b59a7ba04',
    messagingSenderId: '1096466446925',
    projectId: 'renova-52645',
    authDomain: 'renova-52645.firebaseapp.com',
    storageBucket: 'renova-52645.firebasestorage.app',
    measurementId: 'G-WGMG5E5SK8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTjUXFPonQc09U56o7NT1hvFeKYbh_pEU',
    appId: '1:1096466446925:android:c41af3c9ae97f8daa7ba04',
    messagingSenderId: '1096466446925',
    projectId: 'renova-52645',
    storageBucket: 'renova-52645.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyt3-qjtf1qp-GeMK7-QH3JBX0fqz1JSI',
    appId: '1:1096466446925:ios:58b3c357edd56ddfa7ba04',
    messagingSenderId: '1096466446925',
    projectId: 'renova-52645',
    storageBucket: 'renova-52645.firebasestorage.app',
    iosBundleId: 'com.example.renova',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyt3-qjtf1qp-GeMK7-QH3JBX0fqz1JSI',
    appId: '1:1096466446925:ios:58b3c357edd56ddfa7ba04',
    messagingSenderId: '1096466446925',
    projectId: 'renova-52645',
    storageBucket: 'renova-52645.firebasestorage.app',
    iosBundleId: 'com.example.renova',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIguXBt1PM1hpKRnigQcBDS7OYnxydrAY',
    appId: '1:1096466446925:web:ce51fc5636c90ba1a7ba04',
    messagingSenderId: '1096466446925',
    projectId: 'renova-52645',
    authDomain: 'renova-52645.firebaseapp.com',
    storageBucket: 'renova-52645.firebasestorage.app',
    measurementId: 'G-1N0BWV34M2',
  );
}
